CREATE DATABASE Hotel;
GO
USE Hotel;
CREATE TABLE Categoryes
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(30) NOT NULL UNIQUE,
	Price MONEY
);

GO
CREATE TABLE Statuses
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(30) NOT NULL UNIQUE
);
GO
CREATE TABLE Rooms
(
	RoomNumber INT PRIMARY KEY,
	Floor INT NOT NULL,
	Category_Id INT,
	FOREIGN KEY (Category_Id)  REFERENCES Categoryes (Id),
	Status_Id INT,
	FOREIGN KEY (Status_Id)  REFERENCES Statuses (Id)
);
GO
CREATE TABLE KeyCards
(
	Number BIGINT PRIMARY KEY,
	RoomNumber INT NULL,
	FOREIGN KEY (RoomNumber) REFERENCES Rooms(RoomNumber)
);
GO
CREATE TABLE Clients
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Surname NVARCHAR(20) NOT NULL,
	Name NVARCHAR(20) NOT NULL
);
GO
CREATE TABLE Bookings
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	RoomNumber INT NOT NULL,
	FOREIGN KEY (RoomNumber) REFERENCES Rooms(RoomNumber),
	Client_Id INT NOT NULL,
	FOREIGN KEY (Client_Id) REFERENCES Clients(Id),
	CheckInDate DATETIME,
	CheckOutDate DATETIME NULL
);
GO
CREATE TABLE Role
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(30) UNIQUE NOT NULL
);
GO
CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Surname NVARCHAR(20) NOT NULL,
	Name NVARCHAR(20) NOT NULL,
	Role_id INT,
	FOREIGN KEY (Role_id) REFERENCES Role(Id)
);
GO
CREATE TABLE Cleaning
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	RoomNumber INT NOT NULL,
	FOREIGN KEY (RoomNumber) REFERENCES Rooms(RoomNumber),
	User_Id INT NOT NULL,
	FOREIGN KEY (User_Id) REFERENCES Users(Id),
	DateOfHarvesting DATETIME,
	Status BIT
);